import { NextResponse } from 'next/server'

// Sample product data
const sampleProducts = [
  {
    id: '1',
    name: 'Wireless Bluetooth Headphones',
    description: 'High-quality wireless headphones with noise cancellation and long battery life. Features active noise cancellation, 30-hour battery life, and premium comfort for extended listening sessions.',
    price: 89.99,
    originalPrice: 129.99,
    images: ['/api/placeholder/400/400', '/api/placeholder/400/400', '/api/placeholder/400/400'],
    category: 'Audio',
    subcategory: 'Headphones',
    brand: 'SoundMax',
    sku: 'WH-001',
    stock: 45,
    rating: 4.5,
    reviewCount: 128,
    weight: '250g',
    dimensions: '18 x 8 x 20 cm',
    features: [
      'Active Noise Cancellation',
      '30-hour battery life',
      'Bluetooth 5.0',
      'Premium memory foam ear cushions',
      'Built-in microphone',
      'Touch controls'
    ],
    specifications: {
      'Driver Size': '40mm',
      'Frequency Response': '20Hz-20kHz',
      'Impedance': '32Ω',
      'Sensitivity': '105dB',
      'Battery Life': '30 hours',
      'Charging Time': '2 hours'
    },
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
  },
  {
    id: '2',
    name: 'Smart Fitness Watch',
    description: 'Advanced fitness tracking with heart rate monitor and GPS. Monitor your health metrics, track workouts, and stay connected with notifications.',
    price: 199.99,
    originalPrice: 249.99,
    images: ['/api/placeholder/400/400', '/api/placeholder/400/400'],
    category: 'Wearables',
    subcategory: 'Smartwatches',
    brand: 'FitTech',
    sku: 'FW-002',
    stock: 23,
    rating: 4.7,
    reviewCount: 89,
    weight: '45g',
    dimensions: '4.5 x 3.8 x 1.2 cm',
    features: [
      'Heart rate monitoring',
      'GPS tracking',
      '15+ workout modes',
      'Sleep tracking',
      'Water resistant (5ATM)',
      '7-day battery life'
    ],
    specifications: {
      'Display': '1.4" AMOLED',
      'Resolution': '454 x 454 pixels',
      'Battery': '300mAh',
      'Water Resistance': '5ATM',
      'Connectivity': 'Bluetooth 5.0, GPS',
      'Sensors': 'Heart rate, accelerometer, gyroscope'
    },
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
  },
  {
    id: '3',
    name: 'Ultra HD 4K Camera',
    description: 'Professional 4K camera with advanced autofocus and image stabilization. Perfect for content creators, vloggers, and photography enthusiasts.',
    price: 599.99,
    originalPrice: 799.99,
    images: ['/api/placeholder/400/400', '/api/placeholder/400/400', '/api/placeholder/400/400'],
    category: 'Photography',
    subcategory: 'Cameras',
    brand: 'PhotoPro',
    sku: 'UC-003',
    stock: 12,
    rating: 4.8,
    reviewCount: 67,
    weight: '450g',
    dimensions: '12.5 x 8.5 x 6.5 cm',
    features: [
      '4K Ultra HD recording',
      'Advanced autofocus system',
      '5-axis image stabilization',
      'Touchscreen LCD',
      'Built-in Wi-Fi',
      'External microphone input'
    ],
    specifications: {
      'Sensor': '1-inch CMOS',
      'Resolution': '20.1MP',
      'Video': '4K/30p, 1080p/120p',
      'Lens': '24-70mm f/2.8',
      'Stabilization': '5-axis',
      'Connectivity': 'Wi-Fi, Bluetooth, USB-C'
    },
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
  },
  {
    id: '4',
    name: 'Gaming Laptop Pro',
    description: 'High-performance gaming laptop with RTX graphics and fast refresh rate.',
    price: 1299.99,
    originalPrice: 1499.99,
    images: ['/api/placeholder/400/400'],
    category: 'Computers',
    subcategory: 'Laptops',
    brand: 'GameTech',
    sku: 'GL-004',
    stock: 8,
    rating: 4.6,
    reviewCount: 156,
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
  },
  {
    id: '5',
    name: 'Wireless Charging Pad',
    description: 'Fast wireless charging pad compatible with all Qi-enabled devices.',
    price: 29.99,
    originalPrice: 39.99,
    images: ['/api/placeholder/400/400'],
    category: 'Electronics',
    subcategory: 'Chargers',
    brand: 'PowerTech',
    sku: 'WC-005',
    stock: 67,
    rating: 4.3,
    reviewCount: 234,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
  },
  {
    id: '6',
    name: 'Smart Home Hub',
    description: 'Central control hub for all your smart home devices.',
    price: 149.99,
    originalPrice: 199.99,
    images: ['/api/placeholder/400/400'],
    category: 'Electronics',
    subcategory: 'Smart Home',
    brand: 'HomeTech',
    sku: 'SH-006',
    stock: 34,
    rating: 4.4,
    reviewCount: 78,
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
  },
  {
    id: '7',
    name: 'Premium Yoga Mat',
    description: 'Non-slip yoga mat made from eco-friendly materials.',
    price: 49.99,
    originalPrice: 69.99,
    images: ['/api/placeholder/400/400'],
    category: 'Sports',
    subcategory: 'Fitness',
    brand: 'FitLife',
    sku: 'YM-007',
    stock: 89,
    rating: 4.6,
    reviewCount: 145,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
  },
  {
    id: '8',
    name: 'Designer Sunglasses',
    description: 'Stylish sunglasses with UV protection and polarized lenses.',
    price: 129.99,
    originalPrice: 159.99,
    images: ['/api/placeholder/400/400'],
    category: 'Fashion',
    subcategory: 'Accessories',
    brand: 'StyleVision',
    sku: 'SG-008',
    stock: 56,
    rating: 4.5,
    reviewCount: 92,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: false,
  },
]

const categories = [
  { id: '1', name: 'Electronics', subcategories: ['Smartphones', 'Laptops', 'Tablets', 'Smart Home'] },
  { id: '2', name: 'Computers', subcategories: ['Laptops', 'Desktops', 'Components', 'Accessories'] },
  { id: '3', name: 'Photography', subcategories: ['Cameras', 'Lenses', 'Tripods', 'Lighting'] },
  { id: '4', name: 'Audio', subcategories: ['Headphones', 'Speakers', 'Microphones', 'Amplifiers'] },
  { id: '5', name: 'Wearables', subcategories: ['Smartwatches', 'Fitness Trackers', 'VR Headsets'] },
  { id: '6', name: 'Fashion', subcategories: ['Clothing', 'Shoes', 'Accessories', 'Jewelry'] },
  { id: '7', name: 'Sports', subcategories: ['Fitness', 'Outdoor', 'Team Sports', 'Equipment'] },
  { id: '8', name: 'Home & Garden', subcategories: ['Furniture', 'Decor', 'Kitchen', 'Garden'] },
]

export async function GET() {
  // Simulate API delay
  await new Promise(resolve => setTimeout(resolve, 500))
  
  return NextResponse.json({
    products: sampleProducts,
    categories: categories,
  })
}
